<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.api.test.GeneralKeys" tests="1" time="2.014" ignored="6" failures="1" timestamp="26 Apr 2021 19:54:41 GMT" skipped="0" hostname="YASUs-MacBook-Pro.local" errors="0">
  <testcase name="loginAsAUserWithValidCredentials" time="2.014" classname="com.api.test.GeneralKeys">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.api.test.GeneralKeys.loginAsAUserWithValidCredentials(GeneralKeys.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- loginAsAUserWithValidCredentials -->
  <testcase name="returnsAnDeletedApiKey" classname="com.api.test.GeneralKeys">
    <skipped/>
  </testcase> <!-- returnsAnDeletedApiKey -->
  <testcase name="updateASpecificApiKeyEntry" classname="com.api.test.GeneralKeys">
    <skipped/>
  </testcase> <!-- updateASpecificApiKeyEntry -->
  <testcase name="createANewApiKeyEntry" classname="com.api.test.GeneralKeys">
    <skipped/>
  </testcase> <!-- createANewApiKeyEntry -->
  <testcase name="deleteASpecificApiKeyEntry" classname="com.api.test.GeneralKeys">
    <skipped/>
  </testcase> <!-- deleteASpecificApiKeyEntry -->
  <testcase name="returnsAllApiKeyEntries" classname="com.api.test.GeneralKeys">
    <skipped/>
  </testcase> <!-- returnsAllApiKeyEntries -->
  <testcase name="returnsAnApiKeyBasedOnASingleID" classname="com.api.test.GeneralKeys">
    <skipped/>
  </testcase> <!-- returnsAnApiKeyBasedOnASingleID -->
</testsuite> <!-- com.api.test.GeneralKeys -->
